
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package at1_Scanner.minijava;

/** CUP generated class containing symbol constants. */
public class MiniJavaSym {
  /* terminals */
  public static final int LBRACE = 8;
  public static final int PUBLIC = 3;
  public static final int STATIC = 4;
  public static final int MAIN = 6;
  public static final int VOID = 5;
  public static final int EOF = 0;
  public static final int STRING = 7;
  public static final int RBRACK = 13;
  public static final int CLASS_DECL = 2;
  public static final int error = 1;
  public static final int RPAREN = 11;
  public static final int IDENTIFIER = 14;
  public static final int LBRACK = 12;
  public static final int LPAREN = 10;
  public static final int RBRACE = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS_DECL",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "STRING",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "IDENTIFIER"
  };
}

