
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package at1_Scanner.calculadora;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class CalculadoraParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return CalcSym.class;
}

  /** Default constructor. */
  @Deprecated
  public CalculadoraParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public CalculadoraParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public CalculadoraParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\005\000\002\002" +
    "\005\000\002\002\005\000\002\002\005\000\002\002\005" +
    "\000\002\002\005\000\002\002\005\000\002\002\003\000" +
    "\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\024\000\010\004\005\005\004\006\007\001\002\000" +
    "\022\002\ufff8\007\ufff8\010\ufff8\011\ufff8\012\ufff8\013\ufff8" +
    "\014\ufff8\015\ufff8\001\002\000\022\002\ufff9\007\ufff9\010" +
    "\ufff9\011\ufff9\012\ufff9\013\ufff9\014\ufff9\015\ufff9\001\002" +
    "\000\020\002\026\010\011\011\015\012\012\013\016\014" +
    "\017\015\014\001\002\000\010\004\005\005\004\006\007" +
    "\001\002\000\020\007\013\010\011\011\015\012\012\013" +
    "\016\014\017\015\014\001\002\000\010\004\005\005\004" +
    "\006\007\001\002\000\010\004\005\005\004\006\007\001" +
    "\002\000\022\002\ufffa\007\ufffa\010\ufffa\011\ufffa\012\ufffa" +
    "\013\ufffa\014\ufffa\015\ufffa\001\002\000\010\004\005\005" +
    "\004\006\007\001\002\000\010\004\005\005\004\006\007" +
    "\001\002\000\010\004\005\005\004\006\007\001\002\000" +
    "\010\004\005\005\004\006\007\001\002\000\022\002\ufffc" +
    "\007\ufffc\010\ufffc\011\ufffc\012\ufffc\013\ufffc\014\ufffc\015" +
    "\014\001\002\000\022\002\ufffd\007\ufffd\010\ufffd\011\ufffd" +
    "\012\ufffd\013\ufffd\014\ufffd\015\014\001\002\000\022\002" +
    "\uffff\007\uffff\010\uffff\011\uffff\012\012\013\016\014\017" +
    "\015\014\001\002\000\022\002\ufffb\007\ufffb\010\ufffb\011" +
    "\ufffb\012\ufffb\013\ufffb\014\ufffb\015\014\001\002\000\022" +
    "\002\ufffe\007\ufffe\010\ufffe\011\ufffe\012\ufffe\013\ufffe\014" +
    "\ufffe\015\014\001\002\000\022\002\000\007\000\010\000" +
    "\011\000\012\012\013\016\014\017\015\014\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\024\000\004\002\005\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\002\007\001\001" +
    "\000\002\001\001\000\004\002\024\001\001\000\004\002" +
    "\023\001\001\000\002\001\001\000\004\002\022\001\001" +
    "\000\004\002\021\001\001\000\004\002\020\001\001\000" +
    "\004\002\017\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CalculadoraParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CalculadoraParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CalculadoraParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$CalculadoraParser$actions {
  private final CalculadoraParser parser;

  /** Constructor */
  CUP$CalculadoraParser$actions(CalculadoraParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$CalculadoraParser$do_action_part00000000(
    int                        CUP$CalculadoraParser$act_num,
    java_cup.runtime.lr_parser CUP$CalculadoraParser$parser,
    java.util.Stack            CUP$CalculadoraParser$stack,
    int                        CUP$CalculadoraParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CalculadoraParser$result;

      /* select the action based on the action number */
      switch (CUP$CalculadoraParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= expr EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-1)).right;
		Double start_val = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-1)).value;
		RESULT = start_val;
              CUP$CalculadoraParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-1)), ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$CalculadoraParser$parser.done_parsing();
          return CUP$CalculadoraParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // expr ::= expr MAIS expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).right;
		Double e2 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.peek()).value;
		 RESULT = e1 + e2; 
              CUP$CalculadoraParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), RESULT);
            }
          return CUP$CalculadoraParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr ::= expr MENOS expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).right;
		Double e2 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.peek()).value;
		 RESULT = e1 - e2; 
              CUP$CalculadoraParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), RESULT);
            }
          return CUP$CalculadoraParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr ::= expr MULT expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).right;
		Double e2 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.peek()).value;
		 RESULT = e1 * e2; 
              CUP$CalculadoraParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), RESULT);
            }
          return CUP$CalculadoraParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr ::= expr DIV expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).right;
		Double e2 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.peek()).value;
		 RESULT = e1 / e2; 
              CUP$CalculadoraParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), RESULT);
            }
          return CUP$CalculadoraParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= expr INTDIV expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).right;
		Double e2 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.peek()).value;
		 RESULT = (double)(e1.intValue() / e2.intValue()); 
              CUP$CalculadoraParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), RESULT);
            }
          return CUP$CalculadoraParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= expr POT expr 
            {
              Double RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).right;
		Double e1 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).right;
		Double e2 = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.peek()).value;
		 RESULT = Math.pow(e1, e2); 
              CUP$CalculadoraParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), RESULT);
            }
          return CUP$CalculadoraParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= PAREN_ESQ expr PAREN_DIR 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-1)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-1)).value;
		 RESULT = e; 
              CUP$CalculadoraParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.elementAt(CUP$CalculadoraParser$top-2)), ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), RESULT);
            }
          return CUP$CalculadoraParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= NUM_INT 
            {
              Double RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.peek()).value;
		 RESULT = i.doubleValue(); 
              CUP$CalculadoraParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), RESULT);
            }
          return CUP$CalculadoraParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= NUM_FLOAT 
            {
              Double RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$CalculadoraParser$stack.peek()).value;
		 RESULT = f; 
              CUP$CalculadoraParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CalculadoraParser$stack.peek()), RESULT);
            }
          return CUP$CalculadoraParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$CalculadoraParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$CalculadoraParser$do_action(
    int                        CUP$CalculadoraParser$act_num,
    java_cup.runtime.lr_parser CUP$CalculadoraParser$parser,
    java.util.Stack            CUP$CalculadoraParser$stack,
    int                        CUP$CalculadoraParser$top)
    throws java.lang.Exception
    {
              return CUP$CalculadoraParser$do_action_part00000000(
                               CUP$CalculadoraParser$act_num,
                               CUP$CalculadoraParser$parser,
                               CUP$CalculadoraParser$stack,
                               CUP$CalculadoraParser$top);
    }
}

}
